const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#10a37f",
    background: "#f7f7f8",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#10a37f",
    primaryForeground: "#ffffff",
    secondary: "#efefef",
    secondaryForeground: "#1a1a1a",
    muted: "#efefef",
    mutedForeground: "#6e6e80",
    accent: "#efefef",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#ffffff",
    userBubble: "#10a37f",
    userBubbleText: "#ffffff",
    aiBubble: "#ffffff",
    aiBubbleText: "#0a0a0a",
    sourceLink: "#10a37f",
  },
  dark: {
    text: "#ececec",
    tint: "#10a37f",
    background: "#212121",
    foreground: "#ececec",
    card: "#2f2f2f",
    cardForeground: "#ececec",
    primary: "#10a37f",
    primaryForeground: "#ffffff",
    secondary: "#3d3d3d",
    secondaryForeground: "#ececec",
    muted: "#3d3d3d",
    mutedForeground: "#8e8ea0",
    accent: "#3d3d3d",
    accentForeground: "#ececec",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#3d3d3d",
    input: "#2f2f2f",
    userBubble: "#10a37f",
    userBubbleText: "#ffffff",
    aiBubble: "#2f2f2f",
    aiBubbleText: "#ececec",
    sourceLink: "#5cb8a0",
  },
  radius: 16,
};

export default colors;
